%YAML 1.2
---
# Snapcraft Recipe for Tidy
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft syntax
#   https://docs.snapcraft.io/build-snaps/syntax
# * Snap Docs
#   https://snapdocs.labix.org
# * Latest doc topics in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft

name: tidy
summary: HTML parser and pretty printer.  The grand daddy of HTML tools
description: |
  Tidy is a console application for Mac OS X, Linux, Windows, UNIX, and more. It corrects and cleans up HTML and XML documents by fixing markup errors and upgrading legacy code to modern standards.

  This is NOT an official snap, for any issues regarding using this snap please refer to the issue tracker:

  https://github.com/Lin-Buo-Ren/tidy-snap/issues

version: determined-by-version-script
version-script: snap/utilities/set-snap-version.bash

confinement: strict
grade: stable
icon: snap/gui/icon.png

apps:
  tidy:
    command: tidy-launch
    plugs:
    - home
    - removable-media

parts:
  launchers:
    source: snap/launchers

    plugin: dump
    organize:
      tidy-launch: bin/tidy-launch
    stage:
    - bin/*

  tidy:
    source: git://github.com/htacg/tidy-html5.git
    source-depth: 1

    # For stable release build
    source-tag: '5.6.0'

    plugin: cmake
    configflags:
    - -DCMAKE_BUILD_TYPE=Release

    build-packages:
    - build-essential
    - xsltproc

    filesets:
      executables:
      - bin/*
      library-headers:
      - include/*
      library-shared:
      - lib/*.so*
      library-static:
      - lib/*.a
      pkgconfig:
      - lib/pkgconfig/*
      manpages:
      - share/man/*
