%YAML 1.1
---
# Snapcraft Recipe for Tidy
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft syntax
#   https://docs.snapcraft.io/build-snaps/syntax
# * Snap Docs
#   https://snapdocs.labix.org
# * Latest doc topics in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft

name: tidy
summary: HTML parser and pretty printer.  The grand daddy of HTML tools
description: |
  Tidy is a console application for Mac OS X, Linux, Windows, UNIX, and more. It corrects and cleans up HTML and XML documents by fixing markup errors and upgrading legacy code to modern standards.

  This is NOT an official snap, for any issues regarding using this snap please refer to the issue tracker:

  https://github.com/Lin-Buo-Ren/tidy-snap/issues

version: determined-by-version-script
version-script: snap/local/utilities/set-snap-version.bash

confinement: strict
grade: stable
icon: snap/gui/icon.png

apps:
  tidy:
    command: >
      locales-launch
      tidy-launch
      tidy

plugs:
  home:
    read: all
  removable-media:

parts:
  launchers:
    source: snap/local/launchers

    plugin: dump
    organize:
      '*-launch': bin/
    stage:
    - bin/*

  locales-launch:

  tidy:
    source: git://github.com/htacg/tidy-html5.git
    source-depth: 30

    # For official releases
    #source-tag: '5.6.0'

    # For `next` branch releases
    #source-commit: 5f7e367cb54563dabda4bf4e3c11c6ecc68a0fa3

    plugin: cmake
    configflags:
    - -DCMAKE_BUILD_TYPE=Release

    # Disable config files support:
    # https://github.com/htacg/tidy-html5/issues/584
    # * We use the upstream default config instead of the system-wide config(/etc/tidy.conf)
    # * The user config(~/.tinyrc) isn't accessible in the first place due to strict confinement, a hardlink workaround is set in the `tiny-launch` launcher
    - -DENABLE_CONFIG_FILES=OFF

    # DISABLED: Deprecated tool by upstream and no install rule available anyway
    #- -DBUILD_TAB2SPACE=ON

    build-packages:
    - build-essential
    - xsltproc

    filesets:
      executables:
      - bin/*
      library-headers:
      - include/*
      library-shared:
      - lib/*.so*
      library-static:
      - lib/*.a
      pkgconfig:
      - lib/pkgconfig/*
      manpages:
      - share/man/*
